[[SLATEC]]
arch = "aarch64"
git-tree-sha1 = "df84b1dd32d8583825bb2363cfcf3b9ae213e86a"
libgfortran_version = "5.0.0"
os = "macos"

    [[SLATEC.download]]
    sha256 = "90c12bf6967d657e04b467c9e405b8e61a7e2bc576d10391aeb941207145233e"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[SLATEC]]
arch = "aarch64"
git-tree-sha1 = "d207dc19e487da03ae925e0923865989308bd12d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLATEC.download]]
    sha256 = "39bce8d054a7330e9786ef9cde0be77941bf85f7dafe2f6447097d54d8af8adc"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[SLATEC]]
arch = "aarch64"
git-tree-sha1 = "7ec1222ae270e0a7194b73e8683ee048fd3fc6d9"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLATEC.download]]
    sha256 = "aaf6fbfc30515f8faaad7b03ca181d5e92552e7840d4c904a4dc3ccb32d21ffa"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[SLATEC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bc104f5f6d93cd07af3c72e074af76540e95adee"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLATEC.download]]
    sha256 = "35aa226cf193525d7515019d04c682288a4ed7656eee8df9ddefb3e2da0c79ca"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[SLATEC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "aa5eca86fba8c9c5d48a452f41a5c209ca2b5fd9"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLATEC.download]]
    sha256 = "eeef38b04dcd4301bb096d4d3c39f8f06f193cf26c12b223f19c3055aebe2200"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[SLATEC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1604441025bef5c6ec9364a6d4fc38fa95f88a34"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLATEC.download]]
    sha256 = "2811834ed17dae025b0b2ab2a7f404f9386fbe59f66ed0eff04a0628c17bcfe5"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[SLATEC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7e077ecf1d46b285eb386620e504dcca6cc657d0"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLATEC.download]]
    sha256 = "696bcd9ff357dbb63d0dd4378d29c06bcf8677b6ea3596182e53f7f084d04509"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[SLATEC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "16735aeb0a0720a87c5f0a2f99d76bc5d9961c71"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLATEC.download]]
    sha256 = "b286d90208e93ddf7a6af5595f521001bb1af0ddeafbe174cf29dea47e6bf2aa"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[SLATEC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3ced86d4540417fd7ca846331f3b1850865106f0"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLATEC.download]]
    sha256 = "ddfd5f99ae6e3538ac4a07570744758ae73bb1bfd78c10661c9cf4defa81f841"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[SLATEC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9d21ea0a81fab43ddd488f17a4c274727ff648dd"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLATEC.download]]
    sha256 = "53cf439cbf6caae1e9513e29e2984c6a5ae0de1b3aa400d0dd954505376ce129"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[SLATEC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8e6b6a15ea426919232ef8199f9b7780d078d4a1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLATEC.download]]
    sha256 = "ec6898b03c56c671d3796715ce144ea2dd4f1b04d500af1f6667c77eb1346fe2"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[SLATEC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7875eb803977330dc997a3cc78bce05f14cbc251"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLATEC.download]]
    sha256 = "ecfdc4b108bcce7b2520bab0a57114e83a427e164829600c9f8946d0c8e13be8"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[SLATEC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7e2fb545ac6068c9dcdac039be0d5e6b9843b3f5"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLATEC.download]]
    sha256 = "c640201b9ab698b7306d866e2d82a661b541964e0fde3e33e76613354c1760fa"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[SLATEC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ee8c711be60eadad515bb9254baa3e16f7a5bdd0"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLATEC.download]]
    sha256 = "cb3cfc828ef7bb610d514a93f1d75355cffab39e33cd9681d203a02c0ced5b91"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[SLATEC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "408d5d16d7e26bc54b7f95ee88363586d6a15d84"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLATEC.download]]
    sha256 = "fbc0bdc33c0ffb10e59317b3c49131a035daa2ed8f037989ab683571bc24c1ff"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[SLATEC]]
arch = "i686"
git-tree-sha1 = "d6e6ce2134dae2e0330e37cbc6487b9d1e0b1dfa"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLATEC.download]]
    sha256 = "6bc15f251dbefde8645899f6e61ed3343c228e9595b1f3e945d443902231b636"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.i686-linux-gnu-libgfortran3.tar.gz"
[[SLATEC]]
arch = "i686"
git-tree-sha1 = "2fa42b2b9167e38c758176d6c421b9f20b23d7ab"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLATEC.download]]
    sha256 = "6c8313437eded8a68c79df1a73dcfb0256cfa7957479e4f92c901522272f2e8f"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.i686-linux-gnu-libgfortran4.tar.gz"
[[SLATEC]]
arch = "i686"
git-tree-sha1 = "23b609fc6b20e97327e6ca82aabd62f099813190"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLATEC.download]]
    sha256 = "322686ea2c8c8737674c39832a9dca733dcd5b75ad4c985ac7ae17ac268ee10e"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.i686-linux-gnu-libgfortran5.tar.gz"
[[SLATEC]]
arch = "i686"
git-tree-sha1 = "4cdf30d4050870fc54e36c9736d0ce90b4229968"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLATEC.download]]
    sha256 = "e8c28ebc91991672ea1ff327cd713c7641c659e679dbd453ede59282aceaab8e"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.i686-linux-musl-libgfortran3.tar.gz"
[[SLATEC]]
arch = "i686"
git-tree-sha1 = "167ece47c9e0254b7efc71fb258bb5950941afc6"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLATEC.download]]
    sha256 = "e0b0f1a38a741bb0215cb391353ddee494a5133800bb3c62cf667d6c9aa248aa"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.i686-linux-musl-libgfortran4.tar.gz"
[[SLATEC]]
arch = "i686"
git-tree-sha1 = "021236129f64670807ede8a329d5d032af3a84aa"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLATEC.download]]
    sha256 = "0d6a212f19f0019e44dcd3450e1c27b6a6160a1c9a698d5369a7df09e2130e4e"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.i686-linux-musl-libgfortran5.tar.gz"
[[SLATEC]]
arch = "i686"
git-tree-sha1 = "4e05544ff0a9a8be063176bc83c858b43f0f575e"
libgfortran_version = "3.0.0"
os = "windows"

    [[SLATEC.download]]
    sha256 = "0d20a9bd8e31f8b8f9ba82e1136bfe5d78bb9f10c54ee0d96c57041cc37757ee"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[SLATEC]]
arch = "i686"
git-tree-sha1 = "01f1e1eaa9c6cae4439ad3b6c3490470756d98e2"
libgfortran_version = "4.0.0"
os = "windows"

    [[SLATEC.download]]
    sha256 = "7aa1d18c959b6cfcd58a7925b1108637de13a3aae53e1c1b13d2acbe80ac3ce1"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[SLATEC]]
arch = "i686"
git-tree-sha1 = "39157d0136a960345b7af4653547784878b28ea2"
libgfortran_version = "5.0.0"
os = "windows"

    [[SLATEC.download]]
    sha256 = "d4ce259ec3b49b28cbddb3daaa86ed2eb9969e4366b9bca6900741d1d14b2641"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[SLATEC]]
arch = "powerpc64le"
git-tree-sha1 = "63825181c88b3f2dc710cbe47956127635a37d4d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLATEC.download]]
    sha256 = "71e88012ea119ff4009950515a1113e030067941ae11b1cb6f7faa8039307e8c"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[SLATEC]]
arch = "powerpc64le"
git-tree-sha1 = "60ac1bd537919e6e230ef4924de73d89cd905886"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLATEC.download]]
    sha256 = "cbe94a053db791c442f5f81bc3b6b667dd31ab2549ac9d17081af13ca5e85e33"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[SLATEC]]
arch = "powerpc64le"
git-tree-sha1 = "8cb13834a18a34072301f1660f2ca3c64abd60e0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLATEC.download]]
    sha256 = "b4947c58984a34e46b58502927f12a7bfeef7698dd8592d3f96dff8c39f24a6c"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[SLATEC]]
arch = "x86_64"
git-tree-sha1 = "59e1adabe0ecc474f2740a918f5e5dcdafe12cab"
libgfortran_version = "3.0.0"
os = "macos"

    [[SLATEC.download]]
    sha256 = "55aa6b9c44b87138575c305aabbce7e0b8a3398ed5cf734e8434ca7046cf1f39"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.x86_64-apple-darwin-libgfortran3.tar.gz"
[[SLATEC]]
arch = "x86_64"
git-tree-sha1 = "f57347c8add92a2641d68a996ca03d5c57360e1f"
libgfortran_version = "4.0.0"
os = "macos"

    [[SLATEC.download]]
    sha256 = "ee0d8cac3d1caef567eb4241ac9eeb3bd87ecc000313980b76dca85da4d213c4"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[SLATEC]]
arch = "x86_64"
git-tree-sha1 = "95add6ec4eb1902149e6c4e103427f7e3b8a5186"
libgfortran_version = "5.0.0"
os = "macos"

    [[SLATEC.download]]
    sha256 = "e957cc5b031d6584fc06890b8ec7dca1ae4ea0c76338c37ce6518eceba53a2af"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[SLATEC]]
arch = "x86_64"
git-tree-sha1 = "34db1630f4be7f23fb83513a3009c33fbbb8bd76"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLATEC.download]]
    sha256 = "96a4dd5dc8e92984e57bc1a10625a12165adf58d66b359286acb5a5c51cbb972"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[SLATEC]]
arch = "x86_64"
git-tree-sha1 = "a31cbfc6760f85de1868915c6a40463e3e9f6104"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLATEC.download]]
    sha256 = "be47dfb0688d2e9173e1734da5c75f22edb4208a28ecaea4e42e5fca42d5a9a3"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[SLATEC]]
arch = "x86_64"
git-tree-sha1 = "0433a059b7d534320b587cae37e695325c890dae"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLATEC.download]]
    sha256 = "976ab7d527d607a5a22f41bad84d5c007377533d3e8070cfeb94370b664c0bad"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[SLATEC]]
arch = "x86_64"
git-tree-sha1 = "09c20ec5e765767e748f9b81f908e0c51258e5a7"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SLATEC.download]]
    sha256 = "cc74b075a6bb359fea2073d08052d0496bf942e874802d24c1cc0d7f0ec532a2"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[SLATEC]]
arch = "x86_64"
git-tree-sha1 = "523480fc31da91f5a71fd13248b96cef6787a358"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SLATEC.download]]
    sha256 = "87d070d6ed64355c9699049e858cace1ec7aeb16508252c732ecee471a8c6048"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[SLATEC]]
arch = "x86_64"
git-tree-sha1 = "1be67bc0b4f83ab5776620c8be91a159471bd732"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SLATEC.download]]
    sha256 = "aab43ef6d8d74e222efe9bf0ad23616805c65a9f621cf09e4aee3f1f85490505"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[SLATEC]]
arch = "x86_64"
git-tree-sha1 = "88e78f6c0e238a9459f4bb13290b3a2456f60639"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[SLATEC.download]]
    sha256 = "78221a3d18ecd645776c24b6a34249a2c1991c346638c3f5d73a5ed44b56dd09"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[SLATEC]]
arch = "x86_64"
git-tree-sha1 = "5f54315dca84fc5f0b7b34e021eb22d59fe89d0d"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[SLATEC.download]]
    sha256 = "710807d90233d00529238e4c7e06fb549d3a1b62c318522ff1e14271d54e23ea"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[SLATEC]]
arch = "x86_64"
git-tree-sha1 = "b20021e5ce243352508a3e1815b3c12359c01c33"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[SLATEC.download]]
    sha256 = "8fb6bbf4c0fbda09555621975886eed220c3e26cb2d1efc38342e9fe87b465e6"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[SLATEC]]
arch = "x86_64"
git-tree-sha1 = "83885deb9926774ceec505fedf52c36375758f11"
libgfortran_version = "3.0.0"
os = "windows"

    [[SLATEC.download]]
    sha256 = "9d9b523f29a5c8cda8af57de347924cccd23d250ea68ad7bd83bb8017b963d59"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[SLATEC]]
arch = "x86_64"
git-tree-sha1 = "8e1bbd878325b933df2b154329285bd544a2bb5e"
libgfortran_version = "4.0.0"
os = "windows"

    [[SLATEC.download]]
    sha256 = "fa27b2f6a732bc617e4eb7358a4e64e1f2bd62a9ceb0b924b4de68acc874e0d1"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[SLATEC]]
arch = "x86_64"
git-tree-sha1 = "8acc5b6e5544e8dceb0753c97375e14ee0ceb54e"
libgfortran_version = "5.0.0"
os = "windows"

    [[SLATEC.download]]
    sha256 = "f58c55f7ba9ce502968eda7a5ef2bcead36034637abfccc056c6bfb4558830cf"
    url = "https://github.com/JuliaBinaryWrappers/SLATEC_jll.jl/releases/download/SLATEC-v4.1.1+0/SLATEC.v4.1.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
